export {};

declare global {
  interface Window {
    lawcopilotDesktop?: {
      getRuntimeInfo?: () => Promise<Record<string, unknown>>;
      ensureBackend?: (options?: Record<string, unknown>) => Promise<Record<string, unknown>>;
      getStoredConfig?: () => Promise<Record<string, unknown>>;
      saveStoredConfig?: (patch: Record<string, unknown>) => Promise<Record<string, unknown>>;
      getDesktopTtsVoices?: () => Promise<Array<{ id: string; name: string; lang?: string }>>;
      speakText?: (payload: { text: string; voiceId?: string }) => Promise<Record<string, unknown>>;
      stopSpeaking?: () => Promise<Record<string, unknown>>;
      getUpdateStatus?: () => Promise<Record<string, unknown>>;
      checkForUpdates?: () => Promise<Record<string, unknown>>;
      downloadUpdate?: () => Promise<Record<string, unknown>>;
      quitAndInstallUpdate?: () => Promise<Record<string, unknown>>;
      onUpdateStatus?: (listener: (payload: Record<string, unknown>) => void) => (() => void) | void;
      onAutomationEvent?: (listener: (payload: Record<string, unknown>) => void) => (() => void) | void;
      saveLocationSnapshot?: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
      getIntegrationConfig?: () => Promise<Record<string, unknown>>;
      saveIntegrationConfig?: (patch: Record<string, unknown>) => Promise<Record<string, unknown>>;
      saveIntegrationConfigFast?: (patch: Record<string, unknown>) => Promise<Record<string, unknown>>;
      runAssistantLegacySetup?: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
      validateProviderConfig?: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
      getCodexAuthStatus?: () => Promise<Record<string, unknown>>;
      startCodexAuth?: () => Promise<Record<string, unknown>>;
      submitCodexAuthCallback?: (callbackUrl: string) => Promise<Record<string, unknown>>;
      cancelCodexAuth?: () => Promise<Record<string, unknown>>;
      setCodexModel?: (model: string) => Promise<Record<string, unknown>>;
      getGoogleAuthStatus?: () => Promise<Record<string, unknown>>;
      startGoogleAuth?: () => Promise<Record<string, unknown>>;
      submitGoogleAuthCallback?: (callbackUrl: string) => Promise<Record<string, unknown>>;
      cancelGoogleAuth?: () => Promise<Record<string, unknown>>;
      syncGoogleData?: () => Promise<Record<string, unknown>>;
      getGooglePortabilityAuthStatus?: () => Promise<Record<string, unknown>>;
      startGooglePortabilityAuth?: () => Promise<Record<string, unknown>>;
      submitGooglePortabilityAuthCallback?: (callbackUrl: string) => Promise<Record<string, unknown>>;
      cancelGooglePortabilityAuth?: () => Promise<Record<string, unknown>>;
      syncGooglePortabilityData?: () => Promise<Record<string, unknown>>;
      chooseGoogleHistoryArchive?: () => Promise<Record<string, unknown>>;
      importGoogleHistoryArchive?: (filePaths: string[]) => Promise<Record<string, unknown>>;
      getOutlookAuthStatus?: () => Promise<Record<string, unknown>>;
      startOutlookAuth?: () => Promise<Record<string, unknown>>;
      cancelOutlookAuth?: () => Promise<Record<string, unknown>>;
      syncOutlookData?: () => Promise<Record<string, unknown>>;
      sendGmailMessage?: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
      createGoogleCalendarEvent?: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
      validateTelegramConfig?: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
      getTelegramStatus?: () => Promise<Record<string, unknown>>;
      startTelegramWebLink?: () => Promise<Record<string, unknown>>;
      sendTelegramTestMessage?: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
      syncTelegramData?: () => Promise<Record<string, unknown>>;
      getWhatsAppStatus?: () => Promise<Record<string, unknown>>;
      validateWhatsAppConfig?: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
      startWhatsAppWebLink?: () => Promise<Record<string, unknown>>;
      syncWhatsAppData?: () => Promise<Record<string, unknown>>;
      sendWhatsAppMessage?: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
      disconnectWhatsApp?: () => Promise<Record<string, unknown>>;
      getXAuthStatus?: () => Promise<Record<string, unknown>>;
      startXAuth?: () => Promise<Record<string, unknown>>;
      cancelXAuth?: () => Promise<Record<string, unknown>>;
      syncXData?: () => Promise<Record<string, unknown>>;
      postXUpdate?: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
      sendXDirectMessage?: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
      getLinkedInAuthStatus?: () => Promise<Record<string, unknown>>;
      getLinkedInStatus?: () => Promise<Record<string, unknown>>;
      startLinkedInAuth?: () => Promise<Record<string, unknown>>;
      startLinkedInWebLink?: () => Promise<Record<string, unknown>>;
      cancelLinkedInAuth?: () => Promise<Record<string, unknown>>;
      syncLinkedInData?: () => Promise<Record<string, unknown>>;
      postLinkedInUpdate?: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
      getInstagramAuthStatus?: () => Promise<Record<string, unknown>>;
      startInstagramAuth?: () => Promise<Record<string, unknown>>;
      cancelInstagramAuth?: () => Promise<Record<string, unknown>>;
      syncInstagramData?: () => Promise<Record<string, unknown>>;
      sendInstagramMessage?: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
      dispatchApprovedAction?: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
      chooseWorkspaceRoot?: () => Promise<Record<string, unknown>>;
      getWorkspaceConfig?: () => Promise<Record<string, unknown>>;
      saveWorkspaceConfig?: (patch: Record<string, unknown>) => Promise<Record<string, unknown>>;
      openPathInOS?: (relativePath: string) => Promise<Record<string, unknown>>;
      revealPathInOS?: (relativePath: string) => Promise<Record<string, unknown>>;
    };
  }
}
