from __future__ import annotations


ASSISTANT_THREAD_CONTEXT_FETCH_LIMIT = 80
ASSISTANT_THREAD_CONTEXT_WINDOW_MESSAGES = 8
ASSISTANT_THREAD_CONTEXT_MESSAGE_EXCERPT_CHARS = 220
ASSISTANT_THREAD_CONTEXT_WINDOW_CHAR_BUDGET = 2200
ASSISTANT_THREAD_CONTEXT_OLDER_SUMMARY_LIMIT = 4
ASSISTANT_THREAD_EXTERNAL_CONTEXT_LIMIT = 2


def context_policy_dict() -> dict[str, int]:
    return {
        "conversation_fetch_limit": ASSISTANT_THREAD_CONTEXT_FETCH_LIMIT,
        "conversation_window_messages": ASSISTANT_THREAD_CONTEXT_WINDOW_MESSAGES,
        "conversation_message_excerpt_chars": ASSISTANT_THREAD_CONTEXT_MESSAGE_EXCERPT_CHARS,
        "conversation_window_char_budget": ASSISTANT_THREAD_CONTEXT_WINDOW_CHAR_BUDGET,
        "older_summary_limit": ASSISTANT_THREAD_CONTEXT_OLDER_SUMMARY_LIMIT,
        "external_context_limit": ASSISTANT_THREAD_EXTERNAL_CONTEXT_LIMIT,
    }
