from __future__ import annotations

from .models import (
    ConnectorSpec,
    IntegrationActionSpec,
    IntegrationAuthConfig,
    IntegrationPaginationStrategy,
    IntegrationPermissionPreset,
    IntegrationRateLimit,
    IntegrationResourceSpec,
    IntegrationSyncPolicy,
    IntegrationTriggerSpec,
    IntegrationUiField,
    IntegrationUiOption,
    IntegrationWebhookSupport,
)


def _permission_presets() -> list[IntegrationPermissionPreset]:
    return [
        IntegrationPermissionPreset(
            level="read_only",
            label="Salt okuma",
            description="Yalnizca okuma, listeleme, arama ve belge getirme aksiyonlari acilir.",
            allowed_operations=["read", "search", "list_items", "get_item", "read_messages", "fetch_documents", "run_query"],
        ),
        IntegrationPermissionPreset(
            level="read_write",
            label="Okuma ve yazma",
            description="Yazma aksiyonlari acilir ancak degistirici islerde insan onayi zorunludur.",
            allowed_operations=["read", "write", "search", "list_items", "get_item", "create", "update", "send_message", "create_page", "append_block"],
        ),
        IntegrationPermissionPreset(
            level="admin_like",
            label="Genis yetkili",
            description="Silme ve webhook kaydi gibi genis aksiyonlar icin ayrilmis en yuksek erisim duzeyidir.",
            allowed_operations=["read", "write", "delete", "admin"],
        ),
    ]


PERMISSIONS = _permission_presets()


def _action(key: str, title: str, description: str, operation: str, *, access: str = "read", approval_required: bool = False) -> IntegrationActionSpec:
    return IntegrationActionSpec(
        key=key,
        title=title,
        description=description,
        operation=operation,
        access=access,
        approval_required=approval_required,
    )


def _legacy_connector(
    connector_id: str,
    *,
    name: str,
    description: str,
    category: str,
    actions: list[IntegrationActionSpec],
    scopes: list[str] | None = None,
    tags: list[str] | None = None,
    setup_hint: str,
) -> ConnectorSpec:
    return ConnectorSpec(
        id=connector_id,
        name=name,
        description=description,
        category=category,
        auth_type="oauth2",
        auth_config=IntegrationAuthConfig(client_configurable=False, supports_refresh=True),
        scopes=scopes or [],
        resources=[],
        actions=actions,
        triggers=[],
        sync_policies=[
            IntegrationSyncPolicy(mode="incremental", default_strategy="Desktop bridge sync", schedule_hint_minutes=30),
            IntegrationSyncPolicy(mode="manual", default_strategy="Manual refresh from desktop"),
        ],
        pagination_strategy=IntegrationPaginationStrategy(type="cursor"),
        webhook_support=IntegrationWebhookSupport(supported=False),
        rate_limit=IntegrationRateLimit(strategy="unknown"),
        ui_schema=[],
        permissions=PERMISSIONS,
        capability_flags={"read": True, "write": any(action.access != "read" for action in actions), "delete": False},
        management_mode="legacy-desktop",
        default_access_level="read_only",
        tags=tags or [],
        setup_hint=setup_hint,
    )


def _sql_database_connector(
    connector_id: str,
    *,
    name: str,
    description: str,
    default_port: int,
    default_schema: str,
    ssl_options: list[IntegrationUiOption],
    setup_hint: str,
) -> ConnectorSpec:
    return ConnectorSpec(
        id=connector_id,
        name=name,
        description=description,
        category="database",
        auth_type="database",
        auth_config=IntegrationAuthConfig(client_configurable=True, supports_refresh=False),
        scopes=["schemas:read", "tables:read", "rows:read", "rows:write"],
        resources=[
            IntegrationResourceSpec(key="tables", title="Tablolar", description="Schema altindaki tablolar", item_types=["table"], supports_search=True),
            IntegrationResourceSpec(key="rows", title="Kayitlar", description="Tablo satirlari", item_types=["row"]),
        ],
        actions=[
            _action("list_databases", "Schemalari listele", "Schema ve tablo envanterini getirir.", "list_databases"),
            _action("run_query", "Query calistir", "Salt okunur query veya parametrik query calistirir.", "run_query"),
            _action("insert_record", "Kayit ekle", "Yeni satir ekler.", "insert_record", access="write", approval_required=True),
            _action("update_record", "Kayit guncelle", "Varolan satiri gunceller.", "update_record", access="write", approval_required=True),
            _action("delete", "Kayit sil", "Satir siler.", "delete", access="delete", approval_required=True),
        ],
        triggers=[],
        sync_policies=[
            IntegrationSyncPolicy(mode="incremental", default_strategy="updated_at or cursor column", cursor_field="updated_at", schedule_hint_minutes=15),
            IntegrationSyncPolicy(mode="full", default_strategy="Full table snapshot", schedule_hint_minutes=1440),
            IntegrationSyncPolicy(mode="manual", default_strategy="Operator initiated sync"),
        ],
        pagination_strategy=IntegrationPaginationStrategy(type="offset", page_param="offset", page_size_param="limit", items_path="rows"),
        webhook_support=IntegrationWebhookSupport(supported=False),
        rate_limit=IntegrationRateLimit(strategy="unknown"),
        ui_schema=[
            IntegrationUiField(key="connection_label", label="Baglanti etiketi", kind="text", target="config", required=True, placeholder=f"{name} veri kaynagi"),
            IntegrationUiField(key="host", label="Host", kind="text", target="config", required=True, placeholder="db.ornek.local"),
            IntegrationUiField(key="port", label="Port", kind="number", target="config", required=True, default=default_port),
            IntegrationUiField(key="database", label="Database", kind="text", target="config", required=True),
            IntegrationUiField(
                key="schema",
                label="Schema",
                kind="text",
                target="config",
                default=default_schema,
                help_text="MySQL icin bos birakilirsa database adi kullanilir; SQL Server icin varsayilan dbo'dur.",
            ),
            IntegrationUiField(key="username", label="Kullanici adi", kind="text", target="config", required=True),
            IntegrationUiField(key="password", label="Parola", kind="password", target="secret", required=True, secret=True),
            IntegrationUiField(
                key="ssl_mode",
                label="SSL modu",
                kind="select",
                target="config",
                default=str(ssl_options[0].value if ssl_options else "require"),
                options=ssl_options,
            ),
            IntegrationUiField(key="table_allowlist", label="Tablo allowlist", kind="textarea", target="config", placeholder="cases\ncontacts\ncalendar_events"),
        ],
        permissions=PERMISSIONS,
        capability_flags={"read": True, "write": True, "delete": True},
        tags=["database", "sql", "sync", "rag-ready", connector_id],
        setup_hint=setup_hint,
    )


def build_connector_catalog() -> dict[str, ConnectorSpec]:
    web_watch = ConnectorSpec(
        id="web-watch",
        name="Web sayfası takibi",
        description="Belirli web sayfalarını düzenli aralıklarla kontrol eder; değişiklik olduğunda kaydı günceller ve asistan yüzeyine özet düşer.",
        category="web-monitoring",
        auth_type="none",
        auth_config=IntegrationAuthConfig(
            client_configurable=False,
            supports_refresh=False,
            notes=["HTTP ve HTTPS adresleri desteklenir.", "Yerel ağ, localhost ve private host hedefleri güvenlik nedeniyle engellenir."],
        ),
        scopes=[],
        base_url=None,
        resources=[
            IntegrationResourceSpec(
                key="web_pages",
                title="İzlenen sayfalar",
                description="Düzenli aralıklarla kontrol edilen web sayfaları ve içerik özetleri",
                item_types=["document"],
                supports_search=True,
            ),
        ],
        actions=[
            _action("fetch_documents", "Son durumu getir", "Sayfanın son özetini ve çıkarılan içeriği getirir.", "fetch_documents"),
            _action("search", "İçerikte ara", "İzlenen sayfa içeriğinde metin arar.", "search"),
            _action("get_item", "Sayfayı incele", "Sayfanın anlık başlık ve değişim özetini getirir.", "get_item"),
        ],
        triggers=[
            IntegrationTriggerSpec(
                key="page_changed",
                title="Sayfa değişti",
                description="İzlenen web sayfasının içeriği değiştiğinde tetiklenir.",
                event_types=["web.page.changed"],
            ),
        ],
        sync_policies=[
            IntegrationSyncPolicy(mode="incremental", default_strategy="Hash comparison", cursor_field="content_hash", schedule_hint_minutes=1440),
            IntegrationSyncPolicy(mode="manual", default_strategy="On-demand recheck"),
        ],
        pagination_strategy=IntegrationPaginationStrategy(type="none"),
        webhook_support=IntegrationWebhookSupport(supported=False),
        rate_limit=IntegrationRateLimit(strategy="unknown"),
        ui_schema=[
            IntegrationUiField(
                key="watch_label",
                label="Takip adı",
                kind="text",
                target="config",
                required=True,
                placeholder="Resmî Gazete",
                help_text="Bu isim asistanda ve yönetim merkezinde görünür.",
            ),
            IntegrationUiField(
                key="url",
                label="Web adresi",
                kind="url",
                target="config",
                required=True,
                placeholder="https://www.resmigazete.gov.tr/",
                help_text="Takip edilecek sayfanın tam adresini yazın.",
            ),
            IntegrationUiField(
                key="check_interval_minutes",
                label="Kontrol aralığı (dakika)",
                kind="number",
                target="config",
                required=True,
                default=1440,
                help_text="Örneğin 1440 = günde bir kez, 60 = saatte bir kez.",
            ),
            IntegrationUiField(
                key="render_mode",
                label="Tarama modu",
                kind="select",
                target="config",
                required=True,
                default="auto",
                options=[
                    IntegrationUiOption(value="auto", label="Otomatik", description="Önce hızlı tarama, gerekirse tarayıcı desteği"),
                    IntegrationUiOption(value="cheap", label="Hızlı", description="Sadece hafif HTML çıkarımı yapar"),
                    IntegrationUiOption(value="browser", label="Tarayıcı", description="JS ağırlıklı sayfalar için render kullanır"),
                ],
            ),
            IntegrationUiField(
                key="notify_on_change",
                label="Değişiklikte uyar",
                kind="boolean",
                target="config",
                required=True,
                default=True,
                help_text="Değişiklik olduğunda asistan yüzeyinde uyarı kartı gösterilir.",
            ),
            IntegrationUiField(
                key="summary_focus",
                label="Özet odağı",
                kind="textarea",
                target="config",
                required=False,
                placeholder="Yeni kararları, başlık değişimlerini ve dikkat edilmesi gereken duyuruları öne çıkar.",
                help_text="Asistanın bu sayfayı özetlerken hangi değişimlere öncelik vermesi gerektiğini yazabilirsiniz.",
            ),
        ],
        permissions=PERMISSIONS,
        capability_flags={"read": True, "write": False, "delete": False},
        tags=["automation", "monitoring", "web", "documents"],
        docs_url=None,
        setup_hint="Sohbette bir sayfayı takip et demeniz yeterli; URL ve kontrol sıklığını tamamladığınızda asistan düzenli olarak kontrol eder.",
    )

    notion = ConnectorSpec(
        id="notion",
        name="Notion",
        description="Notion workspace, page, database ve block kaynaklarini standart action modeliyle baglar.",
        category="knowledge-base",
        auth_type="bearer",
        auth_config=IntegrationAuthConfig(
            client_configurable=True,
            supports_refresh=False,
            documentation_url="https://developers.notion.com",
            notes=["Workspace tokeni desktop veya local secret store icinde muhurlenir."],
        ),
        scopes=["pages:read", "pages:write", "databases:read", "databases:write"],
        base_url="https://api.notion.com/v1",
        resources=[
            IntegrationResourceSpec(key="pages", title="Sayfalar", description="Notion page nesneleri", item_types=["page"], supports_search=True),
            IntegrationResourceSpec(key="databases", title="Veritabanlari", description="Notion database nesneleri", item_types=["database"], supports_search=True),
            IntegrationResourceSpec(key="blocks", title="Blocklar", description="Page block ve child block yapilari", item_types=["block"]),
        ],
        actions=[
            _action("search", "Ara", "Sayfa ve veritabani icinde arama yapar.", "search"),
            _action("list_items", "Listele", "Sayfa ve veritabani nesnelerini listeler.", "list_items"),
            _action("get_item", "Oge getir", "Belirli bir page veya database kaydini getirir.", "get_item"),
            _action("create_page", "Sayfa olustur", "Yeni sayfa veya child page olusturur.", "create_page", access="write", approval_required=True),
            _action("append_block", "Block ekle", "Varolan sayfaya block ekler.", "append_block", access="write", approval_required=True),
            _action("update", "Guncelle", "Page property veya database row gunceller.", "update", access="write", approval_required=True),
        ],
        triggers=[
            IntegrationTriggerSpec(key="page_updated", title="Sayfa guncellendi", description="Page metadata degisimi", event_types=["page.updated"]),
            IntegrationTriggerSpec(key="database_item_updated", title="Database row guncellendi", description="Database item degisimi", event_types=["database.updated"]),
        ],
        sync_policies=[
            IntegrationSyncPolicy(mode="incremental", default_strategy="Updated time cursor", cursor_field="last_edited_time", schedule_hint_minutes=30),
            IntegrationSyncPolicy(mode="full", default_strategy="Workspace rescan", schedule_hint_minutes=720),
            IntegrationSyncPolicy(mode="manual", default_strategy="On-demand sync"),
        ],
        pagination_strategy=IntegrationPaginationStrategy(type="cursor", cursor_param="start_cursor", page_size_param="page_size", items_path="results"),
        webhook_support=IntegrationWebhookSupport(supported=False),
        rate_limit=IntegrationRateLimit(strategy="unknown"),
        ui_schema=[
            IntegrationUiField(key="workspace_label", label="Workspace etiketi", kind="text", target="config", required=True, placeholder="Muvekkil bilgi merkezi"),
            IntegrationUiField(key="base_url", label="Temel URL", kind="url", target="config", required=True, default="https://api.notion.com/v1"),
            IntegrationUiField(key="notion_version", label="Notion-Version", kind="text", target="config", required=True, default="2022-06-28"),
            IntegrationUiField(key="integration_token", label="Entegrasyon anahtarı", kind="password", target="secret", required=True, secret=True),
        ],
        permissions=PERMISSIONS,
        capability_flags={"read": True, "write": True, "delete": False},
        tags=["knowledge", "notes", "pages", "rag-ready"],
        docs_url="https://developers.notion.com",
        setup_hint="Notion icin ic entegrasyon tokeni yeterlidir; kapsamlar read-only veya read-write olarak ayrilabilir.",
    )

    github = ConnectorSpec(
        id="github",
        name="GitHub",
        description="Repository, issue, pull request ve organization verilerini OAuth2 tabanli lifecycle ile yoneten platform-managed connector.",
        category="developer-tools",
        auth_type="oauth2",
        auth_config=IntegrationAuthConfig(
            client_configurable=True,
            supports_refresh=True,
            authorization_url="https://github.com/login/oauth/authorize",
            token_url="https://github.com/login/oauth/access_token",
            documentation_url="https://docs.github.com/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps",
            default_scopes=["read:user", "read:org", "repo"],
            pkce_required=True,
            notes=["Expiring user token senaryolari icin refresh lifecycle hazirdir."],
        ),
        scopes=["read:user", "read:org", "repo"],
        base_url="https://api.github.com",
        resources=[
            IntegrationResourceSpec(key="repositories", title="Repositoryler", description="Repo metadata ve varsayilan branch bilgileri", item_types=["repository"], supports_search=True),
            IntegrationResourceSpec(key="issues", title="Issue'lar", description="Issue backlog ve etiket verileri", item_types=["issue"], supports_search=True),
            IntegrationResourceSpec(key="pull_requests", title="Pull request'ler", description="PR review ve merge durumu", item_types=["pull_request"], supports_search=True),
        ],
        actions=[
            _action("list_items", "Repositoryleri listele", "Repository ve issue envanterini listeler.", "list_items"),
            _action("get_item", "Oge getir", "Repository, issue veya pull request detayini getirir.", "get_item"),
            _action("search", "Ara", "Repo, issue ve PR icinde arama yapar.", "search"),
            _action("create", "Issue olustur", "Onay sonrasi yeni issue olusturur.", "create", access="write", approval_required=True),
            _action("update", "Issue guncelle", "Onay sonrasi issue veya PR metadata gunceller.", "update", access="write", approval_required=True),
        ],
        triggers=[
            IntegrationTriggerSpec(key="issues", title="Issue eventi", description="Issue acilma veya guncellenme olaylari", event_types=["issues"]),
            IntegrationTriggerSpec(key="pull_request", title="PR eventi", description="Pull request olusum ve review olaylari", event_types=["pull_request"]),
        ],
        sync_policies=[
            IntegrationSyncPolicy(mode="incremental", default_strategy="Updated at cursor", cursor_field="updated_at", schedule_hint_minutes=20),
            IntegrationSyncPolicy(mode="manual", default_strategy="Operator initiated sync"),
        ],
        pagination_strategy=IntegrationPaginationStrategy(type="page", page_param="page", page_size_param="per_page", items_path="items"),
        webhook_support=IntegrationWebhookSupport(
            supported=True,
            signature_header="X-Hub-Signature-256",
            secret_required=True,
            events=["issues", "pull_request", "push"],
        ),
        rate_limit=IntegrationRateLimit(strategy="header", retry_after_header="Retry-After"),
        ui_schema=[
            IntegrationUiField(key="workspace_label", label="Workspace etiketi", kind="text", target="config", required=True, placeholder="Musteri GitHub org"),
            IntegrationUiField(key="client_id", label="Client ID", kind="text", target="config", required=True),
            IntegrationUiField(key="redirect_uri", label="Redirect URI", kind="url", target="config", required=True, placeholder="http://localhost:3000/integrations/callback"),
            IntegrationUiField(key="client_secret", label="Client secret", kind="password", target="secret", required=True, secret=True),
        ],
        permissions=PERMISSIONS,
        capability_flags={"read": True, "write": True, "delete": False},
        tags=["developer", "oauth2", "repositories", "issues"],
        docs_url="https://docs.github.com/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps",
        setup_hint="Client ID, client secret ve redirect URI tanimlandiktan sonra OAuth akisi baslatilabilir.",
    )

    generic_rest = ConnectorSpec(
        id="generic-rest",
        name="Generic REST API",
        description="OpenAPI dokumani olmasa bile REST tabanli ozel servisleri standart action modeliyle baglamak icin temel connector.",
        category="custom-api",
        auth_type="multi",
        auth_config=IntegrationAuthConfig(
            client_configurable=True,
            supports_refresh=False,
            notes=["api_key, bearer, basic veya auth'suz cagri profili secilebilir."],
        ),
        scopes=[],
        resources=[
            IntegrationResourceSpec(key="endpoints", title="Endpointler", description="Kullanici tarafindan tariflenen endpoint listesi", item_types=["endpoint"], supports_search=True),
        ],
        actions=[
            _action("list_items", "Listele", "List endpointlerinden veri ceker.", "list_items"),
            _action("get_item", "Oge getir", "Bir kaydi tekil endpointten getirir.", "get_item"),
            _action("search", "Ara", "Query paramli arama cagrisi yapar.", "search"),
            _action("create", "Olustur", "POST benzeri yazma islemi calistirir.", "create", access="write", approval_required=True),
            _action("update", "Guncelle", "PATCH veya PUT benzeri yazma islemi calistirir.", "update", access="write", approval_required=True),
            _action("delete", "Sil", "DELETE cagrisi calistirir.", "delete", access="delete", approval_required=True),
            _action("download_file", "Dosya indir", "Binary veya belge payloadlarini getirir.", "download_file"),
            _action("upload_file", "Dosya yukle", "Multipart veya binary upload yapar.", "upload_file", access="write", approval_required=True),
        ],
        triggers=[
            IntegrationTriggerSpec(key="webhook", title="Webhook", description="Dis servisin callback tetigi", event_types=["webhook.*"]),
        ],
        sync_policies=[
            IntegrationSyncPolicy(mode="incremental", default_strategy="Cursor or since param", cursor_field="updated_since", schedule_hint_minutes=20),
            IntegrationSyncPolicy(mode="manual", default_strategy="On-demand endpoint crawl"),
        ],
        pagination_strategy=IntegrationPaginationStrategy(type="cursor", cursor_param="cursor", page_param="page", page_size_param="limit", items_path="items"),
        webhook_support=IntegrationWebhookSupport(supported=True, signature_header="X-Signature", secret_required=True, events=["created", "updated", "deleted"]),
        rate_limit=IntegrationRateLimit(strategy="header", retry_after_header="Retry-After"),
        ui_schema=[
            IntegrationUiField(key="service_label", label="Servis etiketi", kind="text", target="config", required=True, placeholder="Dava otomasyon servisi"),
            IntegrationUiField(key="base_url", label="Temel URL", kind="url", target="config", required=True, placeholder="https://api.ornek-servis.com"),
            IntegrationUiField(
                key="auth_mode",
                label="Kimlik dogrulama tipi",
                kind="select",
                target="config",
                required=True,
                default="api_key",
                options=[
                    IntegrationUiOption(value="api_key", label="API anahtari"),
                    IntegrationUiOption(value="bearer", label="Tasiyici anahtar"),
                    IntegrationUiOption(value="basic", label="Temel kimlik dogrulama"),
                    IntegrationUiOption(value="none", label="Kimlik dogrulama yok"),
                ],
            ),
            IntegrationUiField(key="api_key_header", label="API anahtari basligi", kind="text", target="config", default="X-API-Key"),
            IntegrationUiField(key="api_key", label="API anahtari", kind="password", target="secret", secret=True),
            IntegrationUiField(key="bearer_token", label="Tasiyici anahtar", kind="password", target="secret", secret=True),
            IntegrationUiField(key="username", label="Kullanici adi", kind="text", target="config"),
            IntegrationUiField(key="password", label="Parola", kind="password", target="secret", secret=True),
            IntegrationUiField(key="resource_path", label="Kaynak yolu", kind="text", target="config", default="/items", placeholder="/v1/items"),
        ],
        permissions=PERMISSIONS,
        capability_flags={"read": True, "write": True, "delete": True},
        tags=["custom", "rest", "openapi-ready", "scaffoldable"],
        setup_hint="SSRF riskini azaltmak icin lokal/private adresler reddedilir; dokuman URL'si varsa scaffold araci kullanilabilir.",
    )

    postgres = _sql_database_connector(
        "postgresql",
        name="PostgreSQL",
        description="Tablo tabanli veri kaynaklarini query, incremental sync ve index-friendly normalize kayit modeli ile baglar.",
        default_port=5432,
        default_schema="public",
        ssl_options=[
            IntegrationUiOption(value="require", label="Zorunlu"),
            IntegrationUiOption(value="prefer", label="Tercih et"),
            IntegrationUiOption(value="disable", label="Kapali"),
        ],
        setup_hint="Salt okunur erisim icin ayrik kullanici onerilir; delete ve update isleri onay duvarindan gecmelidir.",
    )

    mysql = _sql_database_connector(
        "mysql",
        name="MySQL",
        description="MySQL veya MariaDB veri kaynaklarini tablo envanteri, salt okunur SQL ve kontrollu yazma aksiyonlariyla baglar.",
        default_port=3306,
        default_schema="",
        ssl_options=[
            IntegrationUiOption(value="prefer", label="Tercih et"),
            IntegrationUiOption(value="require", label="Zorunlu"),
            IntegrationUiOption(value="disable", label="Kapali"),
        ],
        setup_hint="Salt okunur kullanici ile baslamak daha guvenlidir; schema bossa database adi kullanilir.",
    )

    mssql = _sql_database_connector(
        "mssql",
        name="SQL Server",
        description="Microsoft SQL Server veritabanlarini schema envanteri, sorgu ve kontrollu kayit isleriyle baglar.",
        default_port=1433,
        default_schema="dbo",
        ssl_options=[
            IntegrationUiOption(value="require", label="Zorunlu"),
            IntegrationUiOption(value="prefer", label="Tercih et"),
            IntegrationUiOption(value="disable", label="Kapali"),
        ],
        setup_hint="SQL Server icin varsayilan schema dbo'dur; ayrik salt okunur kullanici onerilir.",
    )

    elastic = ConnectorSpec(
        id="elastic",
        name="Elastic",
        description="Elastic veya Elasticsearch cluster'larina baglanip indeksleri taramak, belge aramak ve asistanin kullanabilecegi normalize kayitlar uretmek icin baglanti katmani.",
        category="search-engine",
        auth_type="api_key",
        auth_config=IntegrationAuthConfig(client_configurable=True, supports_refresh=False),
        scopes=["indices:read", "documents:read", "documents:write"],
        resources=[
            IntegrationResourceSpec(key="indices", title="Indeksler", description="Index envanteri", item_types=["index"], supports_search=True),
            IntegrationResourceSpec(key="documents", title="Belgeler", description="Index altindaki dokumanlar", item_types=["document"], supports_search=True),
        ],
        actions=[
            _action("search", "Ara", "Elastic query DSL veya basit arama calistirir.", "search"),
            _action("get_item", "Dokuman getir", "Bir dokumani ID ile getirir.", "get_item"),
            _action("run_query", "DSL calistir", "Ham query body ile arama veya agregasyon calistirir.", "run_query"),
            _action("run_sql", "SQL calistir", "Salt okunur Elastic SQL sorgusu calistirir.", "run_sql"),
            _action("insert_record", "Dokuman ekle", "Index'e yeni dokuman yazar.", "insert_record", access="write", approval_required=True),
            _action("update_record", "Dokuman guncelle", "Varolan dokumani gunceller.", "update_record", access="write", approval_required=True),
            _action("delete", "Dokuman sil", "Index'ten dokuman siler.", "delete", access="delete", approval_required=True),
        ],
        triggers=[],
        sync_policies=[
            IntegrationSyncPolicy(mode="incremental", default_strategy="Timestamp cursor or search_after", cursor_field="@timestamp", schedule_hint_minutes=10),
            IntegrationSyncPolicy(mode="manual", default_strategy="Operator initiated sync"),
        ],
        pagination_strategy=IntegrationPaginationStrategy(type="cursor", cursor_param="search_after", page_size_param="size", items_path="hits.hits"),
        webhook_support=IntegrationWebhookSupport(supported=False),
        rate_limit=IntegrationRateLimit(strategy="unknown"),
        ui_schema=[
            IntegrationUiField(key="cluster_label", label="Cluster etiketi", kind="text", target="config", required=True, placeholder="Uretim Elastic"),
            IntegrationUiField(key="base_url", label="Temel URL", kind="url", target="config", required=False, placeholder="https://cluster-ornek.es.europe-west1.gcp.elastic-cloud.com"),
            IntegrationUiField(key="cloud_id", label="Elastic Cloud ID", kind="text", target="config", required=False, placeholder="lawcopilot:dXMtZWFzdC0xLmF3cy5mb3VuZC5pbyR..."),
            IntegrationUiField(key="index_pattern", label="Indeks deseni", kind="text", target="config", required=True, default="cases-*"),
            IntegrationUiField(key="search_fields", label="Aranacak alanlar", kind="text", target="config", required=False, placeholder="title^3, summary^2, body, tags"),
            IntegrationUiField(key="result_size", label="Varsayilan sonuc sayisi", kind="number", target="config", required=False, default=10),
            IntegrationUiField(key="api_key", label="API anahtari", kind="password", target="secret", secret=True),
            IntegrationUiField(key="api_key_id", label="API key ID", kind="text", target="config", required=False),
            IntegrationUiField(key="api_key_secret", label="API key secret", kind="password", target="secret", required=False, secret=True),
            IntegrationUiField(key="username", label="Kullanici adi", kind="text", target="config"),
            IntegrationUiField(key="password", label="Parola", kind="password", target="secret", secret=True),
        ],
        permissions=PERMISSIONS,
        capability_flags={"read": True, "write": True, "delete": True},
        tags=["search", "documents", "analytics"],
        setup_hint="Elastic icin tercihen sadece gerekli indekslere read yetkisi olan API key kullanin. Elastic Cloud kullaniyorsaniz Temel URL yerine Cloud ID de girebilirsiniz.",
    )

    legacy = {
        "gmail": _legacy_connector(
            "gmail",
            name="Gmail",
            description="Mevcut Google masaustu OAuth akisinin mail aynasi.",
            category="communication",
            actions=[
                _action("read_messages", "Mesajlari oku", "Thread ve mail snapshotlarini okur.", "read_messages"),
                _action("send_message", "Mesaj gonder", "Taslak onayi sonrasi mail gonderir.", "send_message", access="write", approval_required=True),
                _action("search", "Ara", "Thread aramasi yapar.", "search"),
            ],
            scopes=["gmail.readonly", "gmail.send"],
            tags=["legacy", "google", "desktop-managed"],
            setup_hint="Kurulum Ayarlar > Kurulum > Google hesabi bolumunde tamamlanir.",
        ),
        "calendar": _legacy_connector(
            "calendar",
            name="Google Calendar",
            description="Mevcut Google Calendar mirror ve planlama akisinin legacy yuzeyi.",
            category="calendar",
            actions=[
                _action("list_items", "Etkinlikleri listele", "Takvim etkinliklerini listeler.", "list_items"),
                _action("create", "Etkinlik olustur", "Onay sonrasi etkinlik olusturur.", "create", access="write", approval_required=True),
                _action("update", "Etkinlik guncelle", "Onay sonrasi etkinlik gunceller.", "update", access="write", approval_required=True),
            ],
            scopes=["calendar.readonly", "calendar.events"],
            tags=["legacy", "google", "desktop-managed"],
            setup_hint="Kurulum Ayarlar > Kurulum > Google hesabi bolumunde tamamlanir.",
        ),
        "drive": _legacy_connector(
            "drive",
            name="Google Drive",
            description="Mevcut Drive dosya aynasinin legacy yuzeyi.",
            category="storage",
            actions=[
                _action("list_items", "Dosyalari listele", "Drive dosyalarini listeler.", "list_items"),
                _action("fetch_documents", "Belgeleri cek", "Belge icerigini baglam icin ceker.", "fetch_documents"),
                _action("search", "Ara", "Dosya aramasi yapar.", "search"),
            ],
            scopes=["drive.readonly"],
            tags=["legacy", "google", "desktop-managed"],
            setup_hint="Kurulum Ayarlar > Kurulum > Google hesabi bolumunde tamamlanir.",
        ),
        "outlook-mail": _legacy_connector(
            "outlook-mail",
            name="Outlook Mail",
            description="Mevcut masaustu Outlook OAuth akisinin mail aynasi.",
            category="communication",
            actions=[
                _action("read_messages", "Mesajlari oku", "Outlook mail thread'lerini okur.", "read_messages"),
                _action("send_message", "Mesaj gonder", "Onay sonrasi mail gonderir.", "send_message", access="write", approval_required=True),
            ],
            scopes=["Mail.Read", "Mail.Send"],
            tags=["legacy", "microsoft", "desktop-managed"],
            setup_hint="Kurulum Ayarlar > Kurulum > Outlook baglantisinda tamamlanir.",
        ),
        "outlook-calendar": _legacy_connector(
            "outlook-calendar",
            name="Outlook Calendar",
            description="Mevcut masaustu Outlook takvim mirror akisinin legacy yuzeyi.",
            category="calendar",
            actions=[
                _action("list_items", "Etkinlikleri listele", "Outlook takvim etkinliklerini listeler.", "list_items"),
                _action("create", "Etkinlik olustur", "Onay sonrasi takvim kaydi olusturur.", "create", access="write", approval_required=True),
            ],
            scopes=["Calendars.Read", "Calendars.ReadWrite"],
            tags=["legacy", "microsoft", "desktop-managed"],
            setup_hint="Kurulum Ayarlar > Kurulum > Outlook baglantisinda tamamlanir.",
        ),
        "telegram": _legacy_connector(
            "telegram",
            name="Telegram",
            description="Bot token tabanli mevcut masaustu bridge akisi.",
            category="communication",
            actions=[
                _action("read_messages", "Mesajlari oku", "Bot uzerinden mesaj aynasi okur.", "read_messages"),
                _action("send_message", "Mesaj gonder", "Bot uzerinden mesaji yollar.", "send_message", access="write", approval_required=True),
            ],
            tags=["legacy", "bot", "desktop-managed"],
            setup_hint="Kurulum Ayarlar > Kurulum > Telegram bolumunde tamamlanir.",
        ),
        "whatsapp": _legacy_connector(
            "whatsapp",
            name="WhatsApp",
            description="Masaustu tarafindaki WhatsApp bridge veya business API akisinin legacy yuzeyi.",
            category="communication",
            actions=[
                _action("read_messages", "Mesajlari oku", "Mesaj aynasini okur.", "read_messages"),
                _action("send_message", "Mesaj gonder", "Onay sonrasi mesaj gonderir.", "send_message", access="write", approval_required=True),
            ],
            tags=["legacy", "messaging", "desktop-managed"],
            setup_hint="Kurulum Ayarlar > Kurulum > WhatsApp bolumunde tamamlanir.",
        ),
        "x": _legacy_connector(
            "x",
            name="X",
            description="Masaustu OAuth ile yonetilen X akisi.",
            category="social",
            actions=[
                _action("search", "Ara", "Mention ve gonderi tarar.", "search"),
                _action("send_message", "DM gonder", "Onay sonrasi DM gonderir.", "send_message", access="write", approval_required=True),
                _action("create", "Gonderi paylas", "Onay sonrasi gonderi paylasir.", "create", access="write", approval_required=True),
            ],
            tags=["legacy", "social", "desktop-managed"],
            setup_hint="Kurulum Ayarlar > Kurulum > X bolumunde tamamlanir.",
        ),
        "instagram": _legacy_connector(
            "instagram",
            name="Instagram",
            description="Masaustu OAuth ile yonetilen Instagram Professional mesajlasma akisi.",
            category="social",
            actions=[
                _action("read_messages", "Mesajlari oku", "Instagram DM konusmalarini okur.", "read_messages"),
                _action("send_message", "Mesaj gonder", "Onay sonrasi Instagram DM yaniti gonderir.", "send_message", access="write", approval_required=True),
                _action("search", "Mesajlarda ara", "Instagram konusmalari icinde arama yapar.", "search"),
            ],
            scopes=["instagram_basic", "instagram_manage_messages", "pages_manage_metadata", "pages_show_list"],
            tags=["legacy", "social", "desktop-managed", "professional-account"],
            setup_hint="Kurulum Ayarlar > Kurulum > Instagram bolumunde tamamlanir.",
        ),
        "linkedin": _legacy_connector(
            "linkedin",
            name="LinkedIn",
            description="Masaustu OAuth ile yonetilen LinkedIn paylasim akisi.",
            category="social",
            actions=[
                _action("create", "Gonderi paylas", "Onay sonrasi gonderi paylasir.", "create", access="write", approval_required=True),
            ],
            tags=["legacy", "social", "desktop-managed"],
            setup_hint="Kurulum Ayarlar > Kurulum > LinkedIn bolumunde tamamlanir.",
        ),
    }

    catalog = {
        web_watch.id: web_watch,
        notion.id: notion,
        github.id: github,
        generic_rest.id: generic_rest,
        postgres.id: postgres,
        mysql.id: mysql,
        mssql.id: mssql,
        elastic.id: elastic,
        **legacy,
    }
    return catalog
