const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("lawcopilotDesktop", {
  getRuntimeInfo: () => ipcRenderer.invoke("lawcopilot:get-runtime-info"),
  ensureBackend: (options) => ipcRenderer.invoke("lawcopilot:ensure-backend", options),
  getStoredConfig: () => ipcRenderer.invoke("lawcopilot:get-desktop-config"),
  saveStoredConfig: (patch) => ipcRenderer.invoke("lawcopilot:save-desktop-config", patch),
  getIntegrationConfig: () => ipcRenderer.invoke("lawcopilot:get-integration-config"),
  saveIntegrationConfig: (patch) => ipcRenderer.invoke("lawcopilot:save-integration-config", patch),
  validateProviderConfig: (payload) => ipcRenderer.invoke("lawcopilot:validate-provider-config", payload),
  getCodexAuthStatus: () => ipcRenderer.invoke("lawcopilot:get-codex-auth-status"),
  startCodexAuth: () => ipcRenderer.invoke("lawcopilot:start-codex-auth"),
  submitCodexAuthCallback: (callbackUrl) => ipcRenderer.invoke("lawcopilot:submit-codex-auth-callback", callbackUrl),
  cancelCodexAuth: () => ipcRenderer.invoke("lawcopilot:cancel-codex-auth"),
  setCodexModel: (model) => ipcRenderer.invoke("lawcopilot:set-codex-model", model),
  getGoogleAuthStatus: () => ipcRenderer.invoke("lawcopilot:get-google-auth-status"),
  startGoogleAuth: () => ipcRenderer.invoke("lawcopilot:start-google-auth"),
  submitGoogleAuthCallback: (callbackUrl) => ipcRenderer.invoke("lawcopilot:submit-google-auth-callback", callbackUrl),
  cancelGoogleAuth: () => ipcRenderer.invoke("lawcopilot:cancel-google-auth"),
  syncGoogleData: () => ipcRenderer.invoke("lawcopilot:sync-google-data"),
  createGoogleCalendarEvent: (payload) => ipcRenderer.invoke("lawcopilot:create-google-calendar-event", payload),
  validateTelegramConfig: (payload) => ipcRenderer.invoke("lawcopilot:validate-telegram-config", payload),
  sendTelegramTestMessage: (payload) => ipcRenderer.invoke("lawcopilot:send-telegram-test-message", payload),
  chooseWorkspaceRoot: () => ipcRenderer.invoke("lawcopilot:choose-workspace-root"),
  getWorkspaceConfig: () => ipcRenderer.invoke("lawcopilot:get-workspace-config"),
  saveWorkspaceConfig: (patch) => ipcRenderer.invoke("lawcopilot:save-workspace-config", patch),
  openPathInOS: (relativePath) => ipcRenderer.invoke("lawcopilot:open-path", relativePath),
  revealPathInOS: (relativePath) => ipcRenderer.invoke("lawcopilot:reveal-path", relativePath),
});
